# Generated by Django 3.1 on 2020-08-12 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Index',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('ticker', models.CharField(max_length=3)),
                ('industry', models.CharField(max_length=30)),
                ('rating', models.CharField(default='NONE', max_length=4)),
                ('index', models.CharField(max_length=30)),
                ('summary', models.TextField(default='additional info about company')),
            ],
        ),
    ]
